version: "3"
services:
  node1:
    extends:
      file: "./besu/node1/docker-compose.yaml"
      service: besu
  node2:
    extends:
      file: "./besu/node2/docker-compose.yaml"
      service: besu

  node3:
    extends:
      file: "./besu/node3/docker-compose.yaml"
      service: besu

  node4:
    extends:
      file: "./besu/node4/docker-compose.yaml"
      service: besu
  
  tesseraNode1:
    extends:
      file: "./tessera/generator/node1/docker-compose.yaml"
      service: tessera

  tesseraNode2:
    extends:
      file: "./tessera/generator/node2/docker-compose.yaml"
      service: tessera

  tesseraNode3:
    extends:
      file: "./tessera/generator/node3/docker-compose.yaml"
      service: tessera

  tesseraNode4:
    extends:
      file: "./tessera/generator/node4/docker-compose.yaml"
      service: tessera

  exploere:
    ports:
      - '8080:80'
    environment:
      - 'APP_NODE_URL=http://localhost:8545'
    image: alethio/ethereum-lite-explorer


  # tesseraGenerator:
  #   extends:
  #     file: "./blockchain/tessera/docker-compose.yaml"
  #     service: node

networks:
  testNet:
    ipam:
      config:
        - subnet: 172.24.0.0/16