version: '3'
services:
  tessera:
    image: quorumengineering/tessera:latest
    container_name: "tessera1"
    volumes:
    - .:/usr/app/
    working_dir: /usr/app/
    command:
        --configfile tessera.conf
    networks:
      testNet:
        ipv4_address: 172.24.0.14
volumes:
  .:
