version: '3'
services:
  besu:
    image: hyperledger/besu:latest
    ports:
      - '30306:30303'
      - '8548:8545'
    environment:
      - BESU_RPC_HTTP_ENABLED=true
    container_name: "besu4"
    volumes:
      - .:/usr/app/
    command: --config-file=/usr/app/option.toml
    networks:
      testNet:
        ipv4_address: 172.24.0.13
volumes:
  .:
